### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by S1xOn6** [lihaoyun6/px-baiduyunpan#12]
Exception: downloadManager.js加载失败

Script Ver: 0.10.6

TemperMonkey Ver: 2.9.4

UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.62 Safari/537.36

**Comment by lihaoyun6** [comment]
脚本已更新, 自动或手动更新脚本后即可正常加载使用
