### ISSUE TITLE
Exception: downloadManager.js加载失败

### ISSUE THREAD

**Issue by WongJin08** [lihaoyun6/px-baiduyunpan#13]
Exception: downloadManager.js加载失败

Script Ver: 0.10.6

TemperMonkey Ver: 4.5

UA: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

**Comment by lihaoyun6** [comment]
更新脚本即可
Please update the script
