### ISSUE TITLE
提交问题

### ISSUE THREAD

**Issue by cybermay** [lihaoyun6/px-baiduyunpan#16]
Exception: downloadManager.js加载失败

Script Ver: 0.10.6

TemperMonkey Ver: 4.6

UA: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

**Comment by lihaoyun6** [comment]
请更新脚本
Please update the script
