### ISSUE TITLE
Exception: downloadManager.js加载失败

### ISSUE THREAD

**Issue by CPUCJ** [lihaoyun6/px-baiduyunpan#17]
Exception: downloadManager.js加载失败
Script Ver: 0.10.6
TemperMonkey Ver: 4.5
UA: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by lihaoyun6** [comment]
请更新脚本
Please update the script
